# Generated by Django 6.0.4 on 2026-04-13 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("himmah", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dayplan",
            name="morning_clarity",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dayplan",
            name="morning_energy",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dayplan",
            name="niyyah_for_allah",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="dayplan",
            name="niyyah_for_self",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="dayplan",
            name="sleep_quality",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dayreview",
            name="barakah_felt",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dayreview",
            name="barakah_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="dayreview",
            name="gratitude_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="distraction",
            name="revisit_after",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weekreview",
            name="average_energy",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=3, null=True
            ),
        ),
        migrations.AddField(
            model_name="weekreview",
            name="average_score",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=3, null=True
            ),
        ),
    ]
