# Generated by Django 6.0.4 on 2026-04-13 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("himmah", "0003_weekreview_best_day_weekreview_worst_day_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE himmah_dayplan
                    ADD CONSTRAINT dayplan_morning_energy_range
                    CHECK (morning_energy >= 1 AND morning_energy <= 5);
                ALTER TABLE himmah_dayplan
                    ADD CONSTRAINT dayplan_morning_clarity_range
                    CHECK (morning_clarity >= 1 AND morning_clarity <= 5);
                ALTER TABLE himmah_dayplan
                    ADD CONSTRAINT dayplan_sleep_quality_range
                    CHECK (sleep_quality >= 1 AND sleep_quality <= 5);
                ALTER TABLE himmah_dayreview
                    ADD CONSTRAINT dayreview_energy_level_range
                    CHECK (energy_level >= 1 AND energy_level <= 5);
                ALTER TABLE himmah_dayreview
                    ADD CONSTRAINT dayreview_score_range
                    CHECK (score >= 1 AND score <= 5);
            """,
            reverse_sql="""
                ALTER TABLE himmah_dayplan DROP CONSTRAINT dayplan_morning_energy_range;
                ALTER TABLE himmah_dayplan DROP CONSTRAINT dayplan_morning_clarity_range;
                ALTER TABLE himmah_dayplan DROP CONSTRAINT dayplan_sleep_quality_range;
                ALTER TABLE himmah_dayreview DROP CONSTRAINT dayreview_energy_level_range;
                ALTER TABLE himmah_dayreview DROP CONSTRAINT dayreview_score_range;
            """,
        ),
    ]
