# Generated by Django 6.0.4 on 2026-04-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('himmah', '0004_fix_energy_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
