# Generated by Django 6.0.4 on 2026-04-15 22:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('himmah', '0005_goal_is_primary'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayplan',
            name='day_start_time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
